[package]
name = "yamd"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Yet Another Markdown (flavor)"
repository = "https://github.com/Lurk/yamd"
readme = "README.md"
keywords = ["markdown", "parser"]

[dev-dependencies]
pretty_assertions = "1.3.0"
